### ISSUE TITLE
"23 errors while parsing DECORATE scripts"

### ISSUE THREAD

**Issue by ChrisCj8** [CloudOfShame/BrutalOblige#1]
Every time I try to launch a wad that has been generated for use with Project Brutality I get this:

OS: Windows NT (NT 10.0) Build 14393
    
M_LoadDefaults: Load system defaults.
Using program directory for storage
W_Init: Init WADfiles.
 adding C:/Users/chris/Desktop/Doom/gzdoom-bin-2-1-1-x64/gzdoom.pk3, 610 lumps
 adding C:/Users/chris/Desktop/Doom/gzdoom-bin-2-1-1-x64/DOOM2.WAD, 2935 lumps
 adding C:/Users/chris/Desktop/Doom/gzdoom-bin-2-1-1-x64/nerve.wad, 108 lumps
 adding C:/Users/chris/Desktop/Doom/Brutal Doom - Hell on Earth Starter Pack/Doom_Metal_Pack_vol4.wad, 66 lumps
 adding C:/Users/chris/Desktop/Doom/wads/randomly generated/test3.wad, 638 lumps
 adding C:/Users/chris/Desktop/Doom/Project_Brutality_2.03a/Project Brutality 2.03.pk3, 20476 lumps
 adding C:/Users/chris/Desktop/Doom/Project_Brutality_2.03a/Project Brutality 2.03.pk3:e2m8.wad, 11 lumps
 adding C:/Users/chris/Desktop/Doom/Project_Brutality_2.03a/Project Brutality 2.03.pk3:e3m8.wad, 11 lumps
 adding C:/Users/chris/Desktop/Doom/Project_Brutality_2.03a/Project Brutality 2.03.pk3:terrain.wad, 260 lumps
 adding C:/Users/chris/Desktop/Doom/Project_Brutality_2.03a/Project Brutality 2.03.pk3:titlemap.wad, 7 lumps
 adding C:/Users/chris/Desktop/Doom/Project_Brutality_2.03a/Project Brutality 2.03.pk3:xhairs.wad, 94 lumps
 adding C:/Users/chris/Desktop/Doom/Project_Brutality_2.03a/External Files/HUDs/UDV/UDV_v1.62_A_BASE_GZDoomOnly.pk3, 1441 lumps
 adding C:/Users/chris/Desktop/Doom/Project_Brutality_2.03a/External Files/HUDs/UDV/UDV_v1.62_A_BASE_GZDoomOnly.pk3:xhairs.wad, 94 lumps
 adding C:/Users/chris/Desktop/Doom/Project_Brutality_2.03a/External Files/HUDs/UDV/UDV_v1.62_B_ADD_IN_Mod_ProjectBrutality.pk3, 23 lumps
 adding C:/Users/chris/Desktop/Doom/Project_Brutality_2.03a/External Files/HUDs/UDV/UDV_v1.62_C_ADD_IN_Misc_Alternate_Visor.pk3, 16 lumps
I_Init: Setting up machine state.
CPU Speed: 3392 MHz
CPU Vendor ID: GenuineIntel
  Name: Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz
  Family 6, Model 58, Stepping 9
  Features: MMX SSE SSE2 SSE3 SSSE3 SSE4.1 SSE4.2
I_InitSound: Initializing FMOD
FMOD Sound System, copyright © Firelight Technologies Pty, Ltd., 1994-2009.
Loaded FMOD version 4.44.61
V_Init: allocate screen.
S_Init: Setting up sound.
ST_Init: Init startup screen.
Checking cmd-line parameters...
S_InitData: Load sound definitions.
G_ParseMapInfo: Load map definitions.
Texman.Init: Init texture manager.
Unknown patch 'SKELJ1' in texture 'SKELPOSTER'
Unknown patch 'FDOKGRIR' in texture 'DOKGRIR'
Unknown patch 'GTGREN01' in texture 'SKINTEK2'
Unknown patch 'FRCAM4' in texture 'A-CAMO4'
Unknown patch 'FRCAM5' in texture 'A-CAMO5'
ANIMDEFS: Can't find FWATER02
ParseTeamInfo: Load team definitions.
LoadActors: Load actor definitions.
Script error, "test3.wad:BRUMONS" line 1:
Parent type 'Trite' not found in ObligeTrite
Script error, "test3.wad:BRUMONS" line 5:
Parent type 'Flemoid1' not found in ObligeFlemoid1
Script error, "test3.wad:BRUMONS" line 9:
Parent type 'Flemoid2' not found in ObligeFlemoid2
Script error, "test3.wad:BRUMONS" line 13:
Parent type 'Flemoid3' not found in ObligeFlemoid3
Script error, "test3.wad:BRUMONS" line 17:
Parent type 'EasyMarine' not found in ObligeEasyMarine
Script error, "test3.wad:BRUMONS" line 21:
Parent type 'Epic2Alien' not found in ObligeEpic2Alien
Script error, "test3.wad:BRUMONS" line 82:
Parent type 'Quadrumpus' not found in ObligeQuadrumpus
Script error, "test3.wad:BRUMONS" line 86:
Parent type 'Nazi' not found in ObligeSS
Script error, "test3.wad:BRUMONS" line 90:
Parent type 'Shadow' not found in ObligeShadow
Script error, "test3.wad:DECORATE" line 5:
Parent type 'PistolAmmo' not found in NilHandGrenadesOblige
Script error, "test3.wad:DECORATE" line 9:
Parent type 'LauncherAmmoSpawner' not found in GrenadeAmmoOblige
Script error, "test3.wad:DECORATE" line 13:
Parent type 'PistolAmmo' not found in NilGrenadeBoxOblige
Script error, "test3.wad:DECORATE" line 17:
Parent type 'LauncherWeaponSpawner' not found in GrenadeLauncherOblige
Script error, "test3.wad:DECORATE" line 21:
Parent type 'PlasmaWeaponSpawner' not found in RailGunOblige
Script error, "test3.wad:DECORATE" line 25:
Parent type 'BFGWeaponSpawner' not found in BFG10KOblige
Script error, "test3.wad:DECORATE" line 29:
Parent type 'PistolAmmo' not found in NilBrutalPistolOblige
Script error, "test3.wad:DECORATE" line 33:
Parent type 'PistolAmmo' not found in Clip2
Script error, "test3.wad:DECORATE" line 37:
Parent type 'ChaingunWeaponSpawner' not found in NilD4MachinegunOblige
Script error, "test3.wad:DECORATE" line 41:
Parent type 'ChaingunWeaponSpawner' not found in NilD4UpgradeBotOblige
Script error, "test3.wad:DECORATE" line 45:
Parent type 'LauncherWeaponSpawner' not found in NilD4GaussCannonOblige
Script error, "test3.wad:DECORATE" line 49:
Parent type 'ChaingunWeaponSpawner' not found in NilBuzzsawOblige
Script error, "test3.wad:DECORATE" line 53:
Parent type 'PistolAmmo' not found in NilPosterOblige
Script error, "test3.wad:DECORATE" line 735:
Parent type 'CurbstompedMarine' not found in Deadd4cacoDemon1
Tried to register class 'RailgunInfrared' more than once.
Bad hex number: no
Bad hex number: no

Execution could not continue.

23 errors while parsing DECORATE scripts

No Idea what could be causing this, am I missing something?

**Comment by CloudOfShame** [comment]
I think I see the problem. I take it that "C:/Users/chris/Desktop/Doom/wads/randomly generated/test3.wad" is the Oblige generated wad? You want to be launching that _after_ C:/Users/chris/Desktop/Doom/Project_Brutality_2.03a/Project Brutality 2.03.pk3

Otherwise you get those Parent type not found errors.

**Comment by ChrisCj8** [comment]
Tried it and it worked, thanks! The Project Brutality Manual told me to load my map-wads before Project Brutality.
