### ISSUE TITLE
Cannot generate maps more than a single level long

### ISSUE THREAD

**Issue by wunshott** [CloudOfShame/BrutalOblige#11]
When attempting to generate a map for any game type (vanilla DOOM 2, PB or BD), oblige throws an error "Script Error: attempt to call global 'Player_max_damage' (a nil value)". I do not get this error if I generate a map with a single level. Any other length returns this error.

It generates levels just fine if I remove the brutal oblige addon. I opened up a thread on the oblige forums and they said try an earlier version of oblige. Going to do that and report back results. 

[ERROR LOG.txt](https://github.com/CloudOfShame/BrutalOblige/files/1449066/ERROR.LOG.txt)

**Comment by CloudOfShame** [comment]
Release 1.0.0 was built against Oblige 7.5 rather than 7.666. This problem will be fixed in the next release, see issue #8
