### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by alphatonic** [CloudOfShame/BrutalOblige#12]
[https://pastebin.com/BV9FK9tT](https://pastebin.com/BV9FK9tT)

Script error, "oblige.wad:DECORATE" line 15:
Parent type 'LauncherAmmoSpawner' not found in GrenadeAmmoOblige

**Comment by CloudOfShame** [comment]
Project Brutality 3.0 is not supported yet and it wont be until there is a public release. The current supported version is 2.03.

**Comment by alphatonic** [comment]
Oh, okay. Thanks for clearing that up. :)
