### ISSUE TITLE
Cannot create maps with brutal or project brutality when Universal Intermission screens addon not present

### ISSUE THREAD

**Issue by Kirussen** [CloudOfShame/BrutalOblige#2]
Hello, I'm getting this after the final map is created and happen without custom settings like smaller spiderdemons. It does the same problem if I choose single player or coop.

Mapinfo code is starting
****** ERROR OCCURRED ******
Stack Trace:
  1: create_mapinfo() @ brutaldoom.lua:983
  2: func() @ brutaldoom.lua:1468
  3: ob_invoke_hook() @ oblige.lua:1003
  4: Level_make_all() @ level.lua:2152
  5: ob_build_cool_shit() @ oblige.lua:1101
Script Error: attempt to index field 'universal_intermissions' (a nil value)
Writing WAD directory
Closed WAD file

**Comment by CloudOfShame** [comment]
I think I've found the cause of that particular error, it's some code I put in to make it compatible with another addon I'm making. I put in a check for whether or not this addon was enabled or not but the check didn't know what to do if the addon wasn't there at all, hence the error. I've improved the check to account for this.

I've tested it on my machine with the addon gone and it worked (initially I was able to recreate the issue you were seeing) so hopefully it should now work for you.

**Comment by Kirussen** [comment]
Thank you, it is now working fine now, also thanks for your hard work. I really like what you did.

**Comment by Kirussen** [comment]
The same problem happened also when I added brutal doom starter pack in the choices.

Mapinfo code is starting
Mapinfo code is running
Starterpack Mapinfo code is running
****** ERROR OCCURRED ******
Stack Trace:
  1: create_mapinfo() @ starterpack.lua:623
  2: func() @ starterpack.lua:768
  3: ob_invoke_hook() @ oblige.lua:1003
  4: Level_make_all() @ level.lua:2152
  5: ob_build_cool_shit() @ oblige.lua:1101
Script Error: attempt to index field 'universal_intermissions' (a nil value)
Writing WAD directory
Closed WAD file

**Comment by CloudOfShame** [comment]
Turns out I was using the exact same dodgy checking code in the starterpack module. Fixed it there. Hopefully that's the only other place...

Thanks for bringing my attention to it.

**Comment by Kirussen** [comment]
No problem, do you want me to try the other choices to see if i get a similar issue?

**Comment by CloudOfShame** [comment]
Yeah that would be great. I do try and test these things on my machine (although I can understand if you're sceptical of that claim) but there will usually be some specific configurations somewhere I'm taking for granted that I probably shouldn't.

**Comment by Kirussen** [comment]
Ok, starter pack module is working. I will test the others now and tell you when i will have done that.

**Comment by CloudOfShame** [comment]
Great thanks. If there are more issues I will try and get fixing them tomorrow, it's getting late where I am.

**Comment by Kirussen** [comment]
For now, i used every options and i got no script errors so i think it's now an old issue. Thank you for the fix.
