### ISSUE TITLE
Missing red key

### ISSUE THREAD

**Issue by Kirussen** [CloudOfShame/BrutalOblige#4]
Hello, i don't know if this problem is by your side but it didn't happen with normal oblige so i will share it with you:

![20170419182727_1](https://cloud.githubusercontent.com/assets/27687576/25205187/49e7ec0e-252f-11e7-8a53-0efc3cb5fd2a.jpg)

I can't pickup the red key and i'm sure it's that one because the only way to continue is by a red door.

Also i would want to ask you if this is missing textures or it's in the game:

![20170418200923_1](https://cloud.githubusercontent.com/assets/27687576/25205214/7405bf0c-252f-11e7-8d99-51194b57c9f0.jpg)

**Comment by CloudOfShame** [comment]
The textures all look fine to me in the seond image, unless I'm missing something?

Re the key that might well be a problem I've introduced. I take it that's Project Brutality rather than Brutal? Does it only happen on Chex maps or is it all of them?

**Comment by Kirussen** [comment]
I get that texture a lot when it is an outside map. I'm happy to know that they are not but it looks really weird.

For the key, it was the first time i saw those textures and it didn't happen before so i guess it is only on Chex maps.

**Comment by CloudOfShame** [comment]
Got it. It was the stupidest thing, I'd made the data for the Chex keys local to the brutaldoom module even though the brutality module needed it. Should be fixed now.

**Comment by Kirussen** [comment]
I will play a new wad and see if it is fixed and let you know.

**Comment by Kirussen** [comment]
I think it's now working, you can see on the right side that is the same wall, also the ceiling is the same. The gun issue, i'm sure it's related to project brutality or brutal doom so not your side. I only get it when i get the regular grenade launcher, after that, all my gun looks like that.

![20170420151638_1](https://cloud.githubusercontent.com/assets/27687576/25248551/abf8b3a8-25dc-11e7-850e-82fc7fad60df.jpg)

**Comment by CloudOfShame** [comment]
Awesome, I'll close the issue.

As for the blue gun I'm guessing that's something to do with the custom HUD. If you let me know what mod that is I'll see if it's possible for me to fix it.

**Comment by Kirussen** [comment]
This one here: http://www.moddb.com/mods/brutal-doom/addons/doomvisor-hud-for-pa1nki113r-v51
