### ISSUE TITLE
Error on game start

### ISSUE THREAD

**Issue by Krigeris** [CloudOfShame/BrutalOblige#7]
Creating the wad works fine but when I attempt to load it in gzdoom I get

ParseTeamInfo: Load team definitions.
LoadActors: Load actor definitions.
Script error, "Rand Small.wad:DARKIMPD" line 208:
Parent type 'XDeathImpArm' not found in XDeathDarkImpArm
Script error, "Rand Small.wad:DARKIMPD" line 212:
Parent type 'XDeathImpHead' not found in XDeathDarkImpHead
Script error, "Rand Small.wad:DARKIMPD" line 216:
Parent type 'ImpXDeath' not found in DarkImpXDeath
Script error, "Rand Small.wad:BRUMONS" line 9:
Parent type 'Belphegor' not found in ObligeBelphegor
Script error, "Rand Small.wad:BRUMONS" line 16:
Parent type 'Hectebus' not found in ObligeJuggernaut
Script error, "Rand Small.wad:BRUMONS" line 23:
Parent type 'Flemoid1' not found in ObligeFlemoid1
Script error, "Rand Small.wad:BRUMONS" line 30:
Parent type 'Flemoid2' not found in ObligeFlemoid2
Script error, "Rand Small.wad:BRUMONS" line 37:
Parent type 'Flemoid3' not found in ObligeFlemoid3
Script error, "Rand Small.wad:BRUMONS" line 44:
Parent type 'EasyMarine' not found in ObligeEasyMarine
Script error, "Rand Small.wad:BRUMONS" line 50:
Parent type 'Epic2Alien' not found in ObligeEpic2Alien
Script error, "Rand Small.wad:BRUMONS" line 114:
Parent type 'Quadrumpus' not found in ObligeQuadrumpus
Script error, "Rand Small.wad:BRUMONS" line 121:
Parent type 'Nazi' not found in ObligeSS
Script error, "Rand Small.wad:BRUMONS" line 128:
Parent type 'TheCyberdemon' not found in BrutalZyberdemon
Script error, "Rand Small.wad:DECORATE" line 5:
Parent type 'HandGrenades' not found in HandGrenadesOblige
Script error, "Rand Small.wad:DECORATE" line 12:
Parent type 'GrenadeAmmo' not found in GrenadeAmmoOblige
Script error, "Rand Small.wad:DECORATE" line 19:
Parent type 'GrenadeBox' not found in GrenadeBoxOblige
Script error, "Rand Small.wad:DECORATE" line 26:
Parent type 'GrenadeLauncher' not found in GrenadeLauncherOblige

Execution could not continue.

Script error, "Rand Small.wad:DECORATE" line 31:
'@property@inventory.pickupmessage' is an unknown actor property

**Comment by CloudOfShame** [comment]
What is your Brutal Doom pk3 file called? If it is anything other than brutalv20b.pk3 you will have to load it manually, before Rand Small.wad

**Comment by Krigeris** [comment]
Thank you, that'd be it.

**Comment by Krigeris** [comment]
Actually, despite swapping out for that file it gives the same error.

**Comment by CloudOfShame** [comment]
Do you get the same result if you try manually loading brutal?

**Comment by Krigeris** [comment]
It seems to play fine when I do the standard drag and drop on the exe method, but when attempting to play via the launcher I use it loads the standard IWAD stages instead. Guessing this is a load order issue now though and not anything to do with the mod, thanks.

**Comment by CloudOfShame** [comment]
Based on the users last comment it seems this was an issue with the launcher they were using. Closing.
